export const DEFAULT_CONTACT_CONTENT = {
  officeTitle: 'Biuro Projektu',
  officeAddress: 'Sielec 1A, 39-120 Sędziszów Małopolski',
  officeHours: 'Biuro projektu czynne jest od poniedziałku do piątku w godzinach 8:00 - 16:00 (istnieje możliwość umówienia się na inne godziny spotkania)',
  contactPerson: '',
  phone: '+48 887 788 064',
  email: 'restartpracy@crse.org.pl',
  facebookUrl: '',
  facebookLabel: 'Restart Pracy',
  organizationName: 'Centrum Rozwoju Społeczno-Ekonomicznego',
  organizationTitle: 'Siedziba Centrum Rozwoju Społeczno-Ekonomicznego - Beneficjent',
  organizationAddress: 'Sielec 1A, 39-120 Sędziszów Małopolski',
  organizationWebsiteUrl: 'https://crse.org.pl',
  organizationWebsiteLabel: 'www.crse.org.pl',
  organizationFacebookUrl: 'https://www.facebook.com/crse.szkolenia/?locale=pl_PL',
  organizationFacebookLabel: 'Centrum Rozwoju Społeczno-Ekonomicznego',
  organizationPhone: '17 22 21 575',
  organizationEmail: 'sekretariat@crse.org.pl',
  hashtags: '#FunduszeUE #FunduszeEuropejskie',
  hashtagsUrl: 'https://www.facebook.com/search/top/?q=%23funduszeue%20%23FunduszeEuropejskie',
  footerText: 'Centrum Rozwoju Społeczno-Ekonomicznego rights reserved.',
};
